- name: restart postgres
  service: name=postgresql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes

- name: restart app
  service: name=hueb state=restarted enabled=yes
  become: yes


- name: restart honeytail
  service: name=honeytail state=restarted enabled=yes
  become: yes
