- name: restart postgres
  service: name=postgresql state=restarted daemon_reload=yes
  become: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart app
  service: name=hueb state=restarted enabled=yes daemon_reload=yes
  become: yes
