- name: Create user database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ user_name }}"

- name: Configure a new postgresql management user
  become: yes
  become_user: postgres
  no_log: yes
  postgresql_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    role_attr_flags: SUPERUSER
  notify:
  - restart postgres

- name: Create django database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ django_db }}"

- name: "Configure a new user for the django db: {{ django_db_user }}"
  become: yes
  become_user: postgres
  no_log: yes
  postgresql_user:
    db: "{{ django_db }}"
    name: "{{ django_db_user }}"
    password: "{{ django_db_password }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER
  notify:
  - restart postgres






