- name: Create user database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ user_name }}"

- name: Configure a new postgresql management user
  become: yes
  become_user: postgres
  no_log: yes
  postgresql_user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    role_attr_flags: SUPERUSER
  notify:
    - restart postgres

- name: Create django database
  become_user: postgres
  become: yes
  postgresql_db:
    name: "{{ django_db }}"

- name: "Configure a new user for the django db: {{ django_db_user }}"
  become: yes
  become_user: postgres
  no_log: yes
  postgresql_user:
    db: "{{ django_db }}"
    name: "{{ django_db_user }}"
    password: "{{ django_db_password }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER
  notify:
    - restart postgres

- name: Configure db_dumps
  template:
    src: ../templates/dump_db.sh.j2
    dest: "/db/dump_db.sh"
  notify:
    - restart app

- name: Make dump_db executable
  file:
    dest: "/db/dump_db.sh"
    mode: a+x

- name: Create cronjob
  cron:
    name: "dump database"
    user: postgres
    minute: "0"
    hour: "0,6,12,18"
    job: "/db/dump_db.sh"
