- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
    state: present

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install postgres
  become: yes
  apt:
    name:
      - postgresql-client-12
      - postgresql-12
      - postgresql-contrib
      - libpq-dev
      - python3-pip
    state: latest

- name: install python dependencies
  become: yes
  pip:
    name:
      - psycopg2
      - virtualenv

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ db_directory }}"
    owner: "postgres"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ db_directory }}/PG_VERSION"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  command: "/usr/lib/postgresql/12/bin/initdb -D {{ db_directory }}"
  when: not pgdata_dir_version.stat.exists
  become: true
  become_user: "postgres"

- name: Start and enable postgres
  service:
    name: postgresql
    enabled: yes
    state: started
