##
# Configure the server for the Django app
##
- name: apply common configuration to server
  hosts: webserver
  become: true
  gather_facts: True
  roles:
    - base
    - database
    - application
    - services
