version: "3.8"

services:
  hueb:
    image: ghcr.io/bockstaller/hueb:${TAG}
    depends_on:
      - database
      - proxy
    volumes:
      - data_directory:/data
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - HUEB_HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
      - SENTRY_API_KEY=${SENTRY_API_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - STATIC_DIR=${STATIC_DIR}
    restart: always
    networks:
      - proxy_network
      - db_network

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - proxy_network

  database:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ${BACKUP_DIR}:/backup
    restart: always
    networks:
      - db_network

networks:
  proxy_network:
  db_network:

volumes:
  database-data:
  data_directory:
