- name: Make migrations
  django_manage:
    app_path: "{{ src_directory }}"
    command: makemigrations
    virtualenv: "{{ venv_directory }}"
  notify:
    - restart app
    - restart nginx

- name: Migrate default database
  django_manage:
    app_path: "{{ src_directory }}"
    command: migrate
    database: default
    virtualenv: "{{ venv_directory }}"
  notify:
    - restart app
    - restart nginx
