

- name: Create a ext4 filesystem on /dev/sdc
  filesystem:
    fstype: ext4
    dev: /dev/sdc

- name: Mount up db_dumps device
  mount:
    path: /db_dumps
    src: /dev/sdb
    fstype: ext4
    state: mounted

- name: Set db_dumps-folder permissions
  file:
    path: "/db_dumps"
    recurse: yes
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: Ansible fact - ansible_date_time
  debug:
    var: ansible_date_time

- name: stop app
  service: name={{app_name}} state=stopped enabled=yes
  become: yes


- name: Dump default database
  become: yes
  become_user: "{{ user_name }}"
  command: "{{venv_directory}}/bin/python3 {{app_directory}}/manage.py dumpdata --database default --output {{dump_directory}}/{{ ansible_date_time.iso8601 }}_default_dump.json"

- name: Dump legacy database
  become: yes
  become_user: "{{ user_name }}"
  command: "{{venv_directory}}/bin/python3 {{app_directory}}/manage.py dumpdata --database legacy_latein --output {{dump_directory}}/{{ ansible_date_time.iso8601 }}_legacy_latein_dump.json"

- name: start app
  service: name={{app_name}} state=started enabled=yes
  become: yes

- name: Compress regular file /path/to/foo into /path/to/foo.gz and remove it
  become: yes
  become_user: "{{ user_name }}"
  archive:
    path: "{{dump_directory}}/{{ ansible_date_time.iso8601 }}_default_dump.json"
    remove: yes


- name: Compress regular file /path/to/foo into /path/to/foo.gz and remove it
  become: yes
  become_user: "{{ user_name }}"
  archive:
    path: "{{dump_directory}}/{{ ansible_date_time.iso8601 }}_legacy_latein_dump.json"
    remove: yes