- name: install the latest version of git
  apt:
    name: git, git-lfs
    state: latest

- name: Create a virtualenv directory
  file:
    path: "{{ app_directory }}"
    state: "directory"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: clone a private repository
  git:
    repo: git@github.com:bockstaller/hueb.git
    dest: "{{ app_directory }}"
    accept_hostkey: yes
    force: yes

- name: Recursively change ownership of a directory
  file:
    path: "{{ app_directory }}"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

