- name: Migrate database
  django_manage:
    app_path: "{{ app_directory }}"
    command: makemigrations
    virtualenv: "{{ venv_directory }}"
  notify:
    - restart app
    - restart nginx

- name: Migrate default database
  django_manage:
    app_path: "{{ app_directory }}"
    command: migrate
    database: default
    virtualenv: "{{ venv_directory }}"
  notify:
    - restart app
    - restart nginx

- name: Migrate legacy database
  django_manage:
    app_path: "{{ app_directory }}"
    command: migrate
    database: legacy_latein
    virtualenv: "{{ venv_directory }}"
  notify:
    - restart app
    - restart nginx

- name: Change permissions for the static directory
  file:
    path: "{{ static_directory }}"
    owner: "{{ user_name }}"
    recurse: yes
    state: directory
    mode: 0744

- name: Get all static files
  django_manage:
    app_path: "{{ app_directory }}"
    command: collectstatic
    virtualenv: "{{ venv_directory }}"
  become: true
  become_user: "{{ user_name }}"
  notify:
    - restart app
    - restart nginx

- name: Change permissions for the static directory
  file:
    path: "{{ static_directory }}"
    owner: "www-data"
    recurse: yes
    state: directory
    mode: 0744