- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install wget
  apt:
    name: wget
    state: latest

- name: Write nginx conf file
  template:
    src: ../templates/hueb.conf
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
  become: yes
  notify:
    - restart nginx
    - restart app

- name: Change permissions for config
  file:
    path: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: "www-data"
    state: file
    mode: 0744
