- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install wget
  apt:
    name: wget
    state: latest

- name: Install honeytail
  become: yes
  shell: wget -q https://honeycomb.io/download/honeytail/linux/honeytail_1.762_amd64.deb && echo 'd7bed8a005cbc6a34b232c54f0f84b945f0bb90905c67f85cceaedee9bbbad1e  honeytail_1.762_amd64.deb' | sha256sum -c && sudo dpkg -i honeytail_1.762_amd64.deb

- name: Write nginx conf file
  template:
    src: ../templates/hueb.conf
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
  become: yes
  notify:
    - restart nginx
    - restart app

- name: Change permissions for config
  file:
    path: /etc/nginx/conf.d/{{ app_name }}.conf
    owner: "www-data"
    state: file
    mode: 0744


- name: Write honeytail conf file
  template:
    src: ../templates/honeytail.j2
    dest: /etc/honeytail/honeytail.conf
  become: yes
  notify:
    - restart honeytail