- name: make backup executable
  become: yes
  file:
    path: "{{ docker_directory }}/postgres/pg_backup.sh"
    owner: ubuntu
    group: docker
    mode: "0770"
    state: file

- name: Create backup directory if it does not exist
  become: yes
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "0770"
    group: docker
    owner: ubuntu
    recurse: yes

- name: create backup
  become: yes
  shell: "sudo ./pg_backup.sh /db_dump/backup"
  args:
    chdir: "{{ docker_directory }}/postgres/"
  environment:
    PGPASSWORD: "{{ db_password }}"
    PGUSER: "{{ db_user }}"
    PGPORT: "{{host_db_port}}"
    POSTGRES_USER: "{{ db_user }}"
